"""FEAT: check for changes to the models

Revision ID: 3b706640cb26
Revises: df1465132480
Create Date: 2025-07-06 18:39:24.027688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b706640cb26'
down_revision: Union[str, Sequence[str], None] = 'df1465132480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('user_wallet_address', sa.String(), nullable=False))
    op.create_index(op.f('ix_models_user_wallet_address'), 'models', ['user_wallet_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_models_user_wallet_address'), table_name='models')
    op.drop_column('models', 'user_wallet_address')
    # ### end Alembic commands ###
