"""FEAT: revert the changes on the ml model

Revision ID: d3b6fbe4df92
Revises: 3b706640cb26
Create Date: 2025-07-06 18:41:53.269720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3b6fbe4df92'
down_revision: Union[str, Sequence[str], None] = '3b706640cb26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('models', 'user_wallet_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('models', 'user_wallet_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
