"""update the ai training jobs

Revision ID: df1465132480
Revises: 3922909088bf
Create Date: 2025-07-06 01:39:20.504560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df1465132480'
down_revision: Union[str, Sequence[str], None] = '3922909088bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_training_jobs', sa.Column('dataset_url', sa.String(), nullable=False))
    op.add_column('ai_training_jobs', sa.Column('file_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_training_jobs', 'file_type')
    op.drop_column('ai_training_jobs', 'dataset_url')
    # ### end Alembic commands ###
