"""added the neew data fields

Revision ID: ed09ba6e4915
Revises: 4339d2e2da21
Create Date: 2025-07-05 18:47:14.287729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed09ba6e4915'
down_revision: Union[str, Sequence[str], None] = '4339d2e2da21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('metadata_cid', sa.String(), nullable=True))
    op.add_column('datasets', sa.Column('dataset_preview_cid', sa.String(), nullable=True))
    op.add_column('datasets', sa.Column('dataset_cid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'dataset_cid')
    op.drop_column('datasets', 'dataset_preview_cid')
    op.drop_column('datasets', 'metadata_cid')
    # ### end Alembic commands ###
